import api
import auth
import blog_entry
import conference
import root
import session_type
import track
import venue
import external_resource
import featured_speaker

assert api
assert auth
assert blog_entry
assert conference
assert root
assert session_type
assert track
assert venue
assert external_resource
assert featured_speaker
